AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Cloudformation Template to allow your parent/payer AWS Account(s) to access
  Kumolus
Parameters:
  RoleName:
    Description: Name of the Role to be created
    Type: String
    Default: Kumolus-CrossAcctRole
Resources:
  CostUsageOrgS3ReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action:
              - cur:DescribeReportDefinitions
              - Organizations:ListAccounts
              - Organizations:ListAccountsForParent
              - Organizations:ListChildren
              - Organizations:ListParents
              - Organizations:ListPolicies
              - Organizations:ListCreateAccountStatus
              - Organizations:DescribeAccount
              - Organizations:DescribeOrganization
              - Organizations:DescribePolicy
              - Organizations:DescribeOrganizationalUnit
              - s3:ListBucket
              - s3:ListAllMyBuckets
            Resource: "*"
  S3ObjectReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action:
              - s3:GetBucketACL
              - s3:GetBucketLocation
              - s3:GetBucketLogging
              - s3:GetBucketPolicy
              - s3:GetBucketTagging
              - s3:GetBucketWebsite
              - s3:GetBucketNotification
              - s3:GetLifecycleConfiguration
              - s3:GetNotificationConfiguration
              - s3:GetObject
            Resource:
              - "arn:aws:s3:::[COST AND USAGE REPORT BUCKET]"
              - "arn:aws:s3:::[COST AND USAGE REPORT BUCKET]/*"
  KumolusCrossAcctRole:
    Type: 'AWS::IAM::Role'
    Description: Cross Account Role for Kumolus Application Access (Payer Account)
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::702574401249:root'
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref CostUsageOrgS3ReadPolicy
        - !Ref S3ObjectReadPolicy
Outputs:
  KumolusRoleARN:
    Description: Role ARN for Kumolus Adapter Configuration
    Value: !GetAtt 
      - KumolusCrossAcctRole
      - Arn
